version: "3.8"
services: 
  api-gateaway:
    container_name: api-gateaway
    build:
      context: ./backend/api-gateaway
      dockerfile: Dockerfile
    env_file:
      - ./backend/api-gateaway/.env
    environment:
      - AUTH_SERVICE_HOST=auth-service
    ports:
      - 3000:3000
    depends_on:
      - auth-service

  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/auth-service/.env
    environment:
      - DATABASE_HOST=auth-service-db
      - DATABASE_PORT=5432
    ports:
      - 3001:3001
    depends_on:
      - auth-service-db

  auth-service-db:
    container_name: auth-service-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xxx
    ports:
      - 5433:5432